### ISSUE TITLE
Support for crystal v1.0.0

### ISSUE THREAD

**Issue by ryanis-online** [crystal-lang/json_mapping.cr#2]
When installing using this shard, I'm presented with the following: `crystal (~> 0.34, >= 0.34.0)` required by `json_mapping 0.1.0`

Is this just a matter of updating the shards.yml file? I'd be happy to submit a pull request for this.

**Comment by owen2345** [comment]
Any news about this?

**Comment by mipmip** [comment]
:+1:

**Comment by bcardiff** [comment]
v0.1.1 has been released
